package com.test.sandev.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.test.sandev.entity.CollectEntity;
import com.test.sandev.entity.BookEntity;

import com.test.sandev.greendao.CollectEntityDao;
import com.test.sandev.greendao.BookEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectEntityDaoConfig;
    private final DaoConfig bookEntityDaoConfig;

    private final CollectEntityDao collectEntityDao;
    private final BookEntityDao bookEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectEntityDaoConfig = daoConfigMap.get(CollectEntityDao.class).clone();
        collectEntityDaoConfig.initIdentityScope(type);

        bookEntityDaoConfig = daoConfigMap.get(BookEntityDao.class).clone();
        bookEntityDaoConfig.initIdentityScope(type);

        collectEntityDao = new CollectEntityDao(collectEntityDaoConfig, this);
        bookEntityDao = new BookEntityDao(bookEntityDaoConfig, this);

        registerDao(CollectEntity.class, collectEntityDao);
        registerDao(BookEntity.class, bookEntityDao);
    }
    
    public void clear() {
        collectEntityDaoConfig.clearIdentityScope();
        bookEntityDaoConfig.clearIdentityScope();
    }

    public CollectEntityDao getCollectEntityDao() {
        return collectEntityDao;
    }

    public BookEntityDao getBookEntityDao() {
        return bookEntityDao;
    }

}
